### PR TITLE
Update mypornclub.py

### PR DESCRIPTION
**Pull request by nindogo**
Did a few changes:
1. Now the search is done based on the number of seeds descending.
2. In some cases the videos have a link on the sxyprn site with the video. I have added a web seed on the magnet link that is just a link to the file on sxyprn. Sometimes that increases the speed of downloads.
3. To be able to see the ones with weblinks I have added an small emoji on the file name so that it is easier to see which ones have links.

### CODE REVIEW

**Comment by BurningMop** [comment]
Please, bump the plugin version. Otherwise, LGTM

**Comment by nindogo** [comment]
So I saw the link on the Unofficial search plugins does not go to this link - that one does not render all names....

**Comment by BurningMop** [comment]
You are missing the second page_url.  I might have forgotten to update the link in the Unofficial search plugins, because I created this repo from the gists itselfs. 

 I plan to add 2 or 3 more search engines during January, and was going to update the page once I've all running.

**Comment by nindogo** [comment]
Should we try threading the additional pages - seems like after some time it doesn't show the rest - although that would probably be considered too much traffic for a large query like say "reagan"?

**Comment by nindogo** [comment]
Threads only show like they are working on the third page or so ...

**Pull request merged**
